# Generated by Django 3.1.2 on 2020-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('hiring_position', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('position_type', models.CharField(choices=[('Internship', 'Internship'), ('Part-Time', 'Part-time'), ('Full-Time', 'Full-time')], default='Internship', max_length=20)),
            ],
        ),
    ]
