# Generated by Django 3.1.2 on 2020-11-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Companies_Interested',
        ),
    ]
