# Generated by Django 3.1.2 on 2020-11-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_auto_20201112_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies_Interested',
            new_name='Company_Application',
        ),
    ]
