# Generated by Django 3.1.2 on 2020-11-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_auto_20201112_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_application',
            name='position_type',
            field=models.CharField(choices=[('- Postion -', '- Postion -'), ('Internship', 'Internship'), ('Part-Time', 'Part-time'), ('Full-Time', 'Full-time')], default='- Postion -', max_length=20),
        ),
    ]
