# Generated by Django 3.1.2 on 2020-11-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_auto_20201112_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_application',
            old_name='job_description',
            new_name='description',
        ),
    ]
